### ISSUE TITLE
(그래서 엔드게임 해적룰렛 오픈소스 레포지토리는 어딨죠?)﻿

### ISSUE THREAD

**Issue by bokmook** [Heptagram/Game-WolfAndSheep#1]
### **제곧네**

<strike>(코드가 궁금해서 진짜로 찾으러 왔어요)</strike>

**Comment by bokmook** [comment]
회신 받으면 더 이상 질문하지 않겠습니다.

<strike>(저도 프로그래밍 합니다! 헤헿)</strike>

**Comment by Heptagram** [comment]
아 자동업로드라 ㅋㅋㅋㅋㅋㅋㅋㅋ 댓글에 게시해두겠습니다.

**Comment by bokmook** [comment]
회신 감사합니다.
